DROP TABLE IF EXISTS TIPO_IDENTIFICACION;
CREATE TABLE TIPO_IDENTIFICACION (
  ID_TIPO_IDENTIFICACION bigint(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  CODIGO varchar(5) DEFAULT NULL,
  DESCRIPCION varchar(255) DEFAULT NULL,
  PRIMARY KEY (ID_TIPO_IDENTIFICACION)
)