/*POBLAR DATOS INICIALES*/
INSERT INTO BIBLIOTECA (ID_BIBLIOTECA, NOMBRE, DIRECCION, TELEFONO,EMAIL) 
VALUES (1,'Biblioteca CEIBA','CLL 65 #12-12', '44440022', 'bibliotecaceiba@gmail.com');

INSERT INTO TIPO_USUARIO (ID_TIPO_USUARIO, TIPO, DESCRIPCION) 
VALUES (1,'1','usuario afiliado'), (2,'2','usuario empleado de la biblioteca'), (3,'3','usuario invitado');

INSERT INTO USUARIO (ID_USUARIO, ID_TIPO_USUARIO, ID_TIPO_IDENTIFICACION, NUMERO_IDENTIFICACION, NOMBRES, APELLIDOS, NUMERO_CELULAR, DIRECCION, EMAIL) 
VALUES (1,'1','1','11122233','Mauricio', 'Restrepo Agudelo', '3004556677', 'call 65 # 15 76','mauricio@gamil.com');

INSERT INTO USUARIO (ID_USUARIO, ID_TIPO_USUARIO, ID_TIPO_IDENTIFICACION, NUMERO_IDENTIFICACION, NOMBRES, APELLIDOS, NUMERO_CELULAR, DIRECCION, EMAIL) 
VALUES (2,'2','1','11122244','Carlos', 'Agudelo Pineda', '3004556677', 'call 65 # 15 76','carlos@gamil.com');

INSERT INTO USUARIO (ID_USUARIO, ID_TIPO_USUARIO, ID_TIPO_IDENTIFICACION, NUMERO_IDENTIFICACION, NOMBRES, APELLIDOS, NUMERO_CELULAR, DIRECCION, EMAIL) 
VALUES (3,'3','1','11122255','Juan', 'Alvarez', '3004556677', 'call 65 # 15 76','juan@gamil.com');

INSERT INTO USUARIO (ID_USUARIO, ID_TIPO_USUARIO, ID_TIPO_IDENTIFICACION, NUMERO_IDENTIFICACION, NOMBRES, APELLIDOS, NUMERO_CELULAR, DIRECCION, EMAIL) 
VALUES (4,'5','1','11122266','Jessica', 'Gracia', '3004556677', 'call 65 # 15 76','jessica@gamil.com');

INSERT INTO LIBRO (ID_LIBRO, ISBN, ID_GENERO_LIBRO, NOMBRE, DESCRIPCION) 
VALUES (1,'1ABSCDF2342','1','Pepipo', 'El libro trata de...');

INSERT INTO PRESTAMO (ID_PRESTAMO, ID_USUARIO, ID_LIBRO, FECHA_PRESTAMO, FECHA_MAXIMA_DEVOLUCION) 
VALUES (1,'1','1','2023-05-05', '2023-05-20');

/*
INSERT INTO TIPO_IDENTIFICACION (ID_TIPO_IDENTIFICACION, CODIGO, DESCRIPCION) 
VALUES (1,'CC','Cédula de ciudadania'),(2,'TI','Tarjeta de identidad');

INSERT INTO GENERO_LIBRO (ID_GENERO_LIBRO, GENERO) 
VALUES (1,'Terror'),(2,'Supenso'),(3,'Fantasia'), (4,'Acción'), (5,'Otro');

DROP TABLE IF EXISTS TIPO_IDENTIFICACION;
CREATE TABLE TIPO_IDENTIFICACION (
  ID_TIPO_IDENTIFICACION bigint(10) PRIMARY KEY,
  CODIGO varchar(10) NOT NULL,
  DESCRIPCION varchar(255) DEFAULT NULL
);

DROP TABLE IF EXISTS GENERO_LIBRO;
CREATE TABLE GENERO_LIBRO (
  ID_GENERO_LIBRO bigint(10) PRIMARY KEY,
  GENERO varchar(50) NOT NULL
);

DROP TABLE IF EXISTS TIPO_USUARIO;
CREATE TABLE TIPO_USUARIO (
  ID_TIPO_USUARIO bigint(10) PRIMARY KEY,
  TIPO varchar(50) NOT NULL,
  DESCRIPCION varchar(255) DEFAULT NULL
);


DROP TABLE IF EXISTS BIBLIOTECA;
CREATE TABLE BIBLIOTECA (
  ID_BIBLIOTECA bigint(10) PRIMARY KEY,
  NOMBRE varchar(255) NOT NULL,
  DIRECCION varchar(255) NOT NULL,
  TELEFONO varchar(255) NOT NULL,
  EMAIL varchar(255) DEFAULT NULL,
  PRIMARY KEY (ID_BIBLIOTECA)
);

DROP TABLE IF EXISTS USUARIO;
CREATE TABLE USUARIO (
  ID_USUARIO bigint(10) PRIMARY KEY,
  ID_TIPO_USUARIO bigint(10) NOT NULL,
  ID_TIPO_IDENTIFICACION bigint(10) NOT NULL,
  NUMERO_IDENTIFICACION varchar(255) NOT NULL,
  NOMBRES varchar(255) NOT NULL,
  APELLIDOS varchar(255) NOT NULL,
  NUMERO_CELULAR varchar(255) NOT NULL,
  DIRECCION varchar(255) NOT NULL,
  EMAIL varchar(255) DEFAULT NULL,
  PRIMARY KEY (ID_USUARIO),
  FOREIGN KEY (ID_TIPO_IDENTIFICACION) REFERENCES Persons(ID_TIPO_IDENTIFICACION),
  FOREIGN KEY (ID_TIPO_USUARIO) REFERENCES Persons(ID_TIPO_USUARIO)
)

DROP TABLE IF EXISTS LIBRO;
CREATE TABLE LIBRO (
  ID_LIBRO bigint(10) PRIMARY KEY,
  ISBN varchar(10) NOT NULL,
  ID_GENERO_LIBRO varchar(255) NOT NULL,
  NOMBRE varchar(255) NOT NULL,
  DESCRIPCION varchar(255) DEFAULT NULL,
  PRIMARY KEY (ID_LIBRO),
  FOREIGN KEY (ID_GENERO_LIBRO) REFERENCES Persons(ID_GENERO_LIBRO)
)

DROP TABLE IF EXISTS PRESTAMO;
CREATE TABLE PRESTAMO (
  ID_PRESTAMO bigint(10) PRIMARY KEY,
  ID_USUAIRO bigint(10) NOT NULL,
  ID_LIBRO bigint(10) NOT NULL,
  FECHA_PRESTAMO DATE NOT NULL,
  FECHA_MAXIMA_DEVOLUCION varchar(255) NOT NULL,
  PRIMARY KEY (ID_BIBLIOTECA),
  FOREIGN KEY (ID_USUAIRO) REFERENCES Persons(ID_USUAIRO),
  FOREIGN KEY (ID_LIBRO) REFERENCES Persons(ID_LIBRO)
)
*/
