version: "3.8"
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-lts
    privileged: true
    user: root
    ports:
      - 8081:8080
      - 50001:50000
    volumes:
      - ~/Documentos/volume-jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
#mrestrepoagu-socrates